# Generated by Django 3.2 on 2024-12-16 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('lienImageConsommable', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defaillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaireDefaillance', models.CharField(blank=True, max_length=1000, null=True)),
                ('niveau', models.CharField(max_length=50, validators=[myApp.models.validate_niveau_de_defaillance])),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDocumentTechnique', models.CharField(max_length=50)),
                ('lienDocumentTechnique', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFabricant', models.CharField(max_length=50)),
                ('paysFabricant', models.CharField(max_length=50)),
                ('mailFabricant', models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()])),
                ('numTelephoneFabricant', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone non valide', regex='^\\+?1?\\d{9,15}$')])),
                ('serviceApresVente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomFournisseur', models.CharField(max_length=50)),
                ('numRue', models.SmallIntegerField()),
                ('nomRue', models.CharField(max_length=50)),
                ('codePostal', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('paysFournisseur', models.CharField(max_length=50)),
                ('mailFournisseur', models.EmailField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator()])),
                ('numTelephoneFournisseur', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone non valide', regex='^\\+?1?\\d{9,15}$')])),
                ('serviceApresVente', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRole', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomUtilisateur', models.CharField(max_length=50)),
                ('motDePasse', models.CharField(max_length=100)),
                ('mailUtilisateur', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('numTelephoneUtilisateur', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone non valide', regex='^\\+?1?\\d{9,15}$')])),
                ('actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StockConsommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prixAchat', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dateAchat', models.DateField()),
                ('quantiteConsommable', models.SmallIntegerField()),
                ('commentaire', models.CharField(blank=True, max_length=1000, null=True)),
                ('idConsommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.consommable')),
                ('idFournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='ModeleEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomModeleEquipement', models.CharField(max_length=50)),
                ('idFabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLieu', models.CharField(max_length=50)),
                ('typeLieu', models.CharField(max_length=50)),
                ('idLieuParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomIntervention', models.CharField(blank=True, max_length=50, null=True)),
                ('interventionCurative', models.BooleanField(blank=True, null=True)),
                ('dateAssignation', models.DateTimeField()),
                ('dateCloture', models.DateTimeField()),
                ('dateDebutIntervention', models.DateTimeField(blank=True, null=True)),
                ('dateFinIntervention', models.DateTimeField(blank=True, null=True)),
                ('tempsEstime', models.TimeField(blank=True, null=True)),
                ('commentaireIntervention', models.CharField(blank=True, max_length=1000, null=True)),
                ('idCreateurIntervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createurIntervention', to='myApp.utilisateur')),
                ('idDefaillance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.defaillance')),
                ('idResponsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='myApp.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='InformationMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preventifGlissant', models.BooleanField(blank=True, null=True)),
                ('joursIntervalleMaintenance', models.SmallIntegerField()),
                ('dateCreation', models.DateTimeField()),
                ('dateChangement', models.DateTimeField(blank=True, null=True)),
                ('idCreateurInformationMaintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.utilisateur')),
                ('idInformationMaintenanceParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.informationmaintenance')),
            ],
        ),
        migrations.CreateModel(
            name='EstCompatible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idConsommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.consommable')),
                ('idModeleEquipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.modeleequipement')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField()),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('dateMiseEnService', models.DateField()),
                ('prixAchat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lienImageEquipement', models.URLField(blank=True, max_length=100, null=True)),
                ('statutEquipement', models.CharField(blank=True, max_length=50, null=True)),
                ('idCreateurEquipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createurEquipement', to='myApp.utilisateur')),
                ('idFournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.fournisseur')),
                ('idInformationMaintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.informationmaintenance')),
                ('idLieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.lieu')),
                ('idModeleEquipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.modeleequipement')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDocumentIntervention', models.CharField(max_length=50)),
                ('lienDocumentIntervention', models.URLField(max_length=100)),
                ('idIntervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDefaillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDocumentDefaillance', models.CharField(max_length=50)),
                ('lienDocumentDefaillance', models.URLField(max_length=100)),
                ('idDefaillance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.defaillance')),
            ],
        ),
        migrations.AddField(
            model_name='defaillance',
            name='idEquipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.equipement'),
        ),
        migrations.AddField(
            model_name='defaillance',
            name='idUtilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.utilisateur'),
        ),
        migrations.CreateModel(
            name='Correspondre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDocumentTechnique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.documenttechnique')),
                ('idModeleEquipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.modeleequipement')),
            ],
        ),
        migrations.CreateModel(
            name='Constituer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idConsommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.consommable')),
                ('idEquipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.equipement')),
            ],
        ),
        migrations.AddField(
            model_name='consommable',
            name='idFabricant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.fabricant'),
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.role')),
                ('idUtilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.utilisateur')),
            ],
        ),
    ]
